# Generated by Django 6.0.5 on 2026-05-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AramaGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebat', models.CharField(max_length=30)),
                ('marka', models.CharField(blank=True, max_length=50)),
                ('mevsim', models.CharField(blank=True, max_length=20)),
                ('arama_zamani', models.DateTimeField(auto_now_add=True)),
                ('sonuc_sayisi', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-arama_zamani'],
            },
        ),
    ]
