# Generated by Django 6.0.5 on 2026-06-12 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karsilastirma', '0002_abonelik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarih', models.DateField()),
                ('yontem', models.CharField(choices=[('nakit', 'Nakit'), ('havale', 'Havale / EFT'), ('kredi_karti', 'Kredi Kartı'), ('diger', 'Diğer')], default='havale', max_length=20)),
                ('aciklama', models.TextField(blank=True, help_text='Dekont no, dönem vb.')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odemeler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-tarih'],
            },
        ),
    ]
