# Generated by Django 6.0.5 on 2026-06-16 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karsilastirma', '0004_aramagecmisi_kullanici'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebat', models.CharField(blank=True, max_length=30)),
                ('marka', models.CharField(blank=True, max_length=80)),
                ('icerik', models.TextField()),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('silinme', models.DateTimeField()),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Not',
                'verbose_name_plural': 'Notlar',
                'ordering': ['-olusturulma'],
            },
        ),
    ]
