# Generated by Django 6.0.5 on 2026-06-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karsilastirma', '0005_notlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonelik',
            name='session_key',
            field=models.CharField(blank=True, default='', help_text='Aktif session key — tek oturum kontrolü için', max_length=40),
        ),
    ]
