# Generated by Django 6.0.5 on 2026-06-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karsilastirma', '0006_abonelik_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonelik',
            name='plan',
            field=models.CharField(choices=[('aylik', 'Aylık'), ('yillik', 'Yıllık'), ('demo', 'Demo'), ('deneme', 'Deneme')], default='demo', max_length=10),
        ),
    ]
