# Generated by Django 6.0.5 on 2026-06-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karsilastirma', '0007_deneme_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToptanciIskonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toptanci_adi', models.CharField(help_text="Toptancı adı (views.py'deki B2B_LINKLER ile eşleşmeli)", max_length=60, unique=True)),
                ('iskonto_metni', models.TextField(blank=True, help_text="Tooltip'te gösterilecek iskonto/not metni. Boşsa tooltip çıkmaz.")),
                ('guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Toptancı İskonto',
                'verbose_name_plural': 'Toptancı İskontolar',
                'ordering': ['toptanci_adi'],
            },
        ),
    ]
