# Generated by Django 6.0.5 on 2026-06-23 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karsilastirma', '0008_toptanci_iskonto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='toptanciiskonto',
            name='kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iskontolar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='toptanciiskonto',
            name='iskonto_metni',
            field=models.TextField(blank=True, help_text="Tooltip'te gösterilecek iskonto/not metni."),
        ),
        migrations.AlterField(
            model_name='toptanciiskonto',
            name='toptanci_adi',
            field=models.CharField(help_text='Toptancı adı (B2B_LINKLER ile eşleşmeli)', max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='toptanciiskonto',
            unique_together={('kullanici', 'toptanci_adi')},
        ),
    ]
