# Generated by Django 4.2.16 on 2026-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karsilastirma', '0009_toptanci_iskonto_kullanici'),
    ]

    operations = [
        migrations.AddField(
            model_name='notlar',
            name='musteri',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
